apiVersion: v1
kind: ConfigMap
metadata:
  name: flyte-sandbox-config
  namespace: flyte
data:
  001-plugins.yaml: |
    tasks:
      task-plugins:
        default-for-task-types:
          container: container
          container_array: k8s-array
          sidecar: sidecar
        enabled-plugins:
        - container
        - sidecar
        - k8s-array
        - agent-service
    plugins:
      logs:
        kubernetes-enabled: true
        kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
        cloudwatch-enabled: false
        stackdriver-enabled: false
      k8s:
        co-pilot:
          image: "cr.flyte.org/flyteorg/flytecopilot:v1.10.6"
      k8s-array:
        logs:
          config:
            kubernetes-enabled: true
            kubernetes-template-uri: http://localhost:30080/kubernetes-dashboard/#/log/{{.namespace }}/{{ .podName }}/pod?namespace={{ .namespace }}
            cloudwatch-enabled: false
            stackdriver-enabled: false
      agent-service:
        defaultAgent:
          defaultTimeout: 10s
          endpoint: dns:///flyteagent.flyte.svc.cluster.local:8000
          insecure: true
          timeouts:
            GetTask: 10s
        supportedTaskTypes:
        - default_task
